[build]
  base = "nextemp-main"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: fallback for unsupported pages
[[redirects]]
  from = "/*"
  to = "/"
  status = 200