[build]
  base    = "nextemp-main"
  command = "npm run build"
  publish = "nextemp-main/out"  # or .next or build, depending on your setup


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
