[build]
  base    = "nextemp-main"
  command = "npm run build"
  publish = "nextemp-main/.next"

[[plugins]]
  package = "@netlify/next"

# Optional: fallback for unsupported pages
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
